export const CATEGORIES = ['All', 'Script', 'Serif', 'Sans', 'Arabic', 'CJK', 'Other']

export const FONTS = [
  // Script / Handwriting
  { name: 'Dancing Script',         category: 'Script' },
  { name: 'Great Vibes',            category: 'Script' },
  { name: 'Satisfy',                category: 'Script' },
  { name: 'Caveat',                 category: 'Script' },
  { name: 'Sacramento',             category: 'Script' },
  { name: 'Pacifico',               category: 'Script' },
  { name: 'Allura',                 category: 'Script' },
  { name: 'Alex Brush',             category: 'Script' },
  { name: 'Pinyon Script',          category: 'Script' },
  { name: 'Italianno',              category: 'Script' },
  { name: 'Tangerine',              category: 'Script' },
  { name: 'Cookie',                 category: 'Script' },
  { name: 'Kaushan Script',         category: 'Script' },
  { name: 'Lobster',                category: 'Script' },
  { name: 'Yellowtail',             category: 'Script' },
  { name: 'Shadows Into Light',     category: 'Script' },
  { name: 'Homemade Apple',         category: 'Script' },
  { name: 'Rock Salt',              category: 'Script' },
  { name: 'Permanent Marker',       category: 'Script' },
  { name: 'Kristi',                 category: 'Script' },
  { name: 'Euphoria Script',        category: 'Script' },
  { name: 'Norican',                category: 'Script' },
  { name: 'Marck Script',           category: 'Script' },
  { name: 'Niconne',                category: 'Script' },
  { name: 'Grand Hotel',            category: 'Script' },
  { name: 'Monsieur La Doulaise',   category: 'Script' },
  { name: 'Mr De Haviland',         category: 'Script' },
  { name: 'Princess Sofia',         category: 'Script' },
  { name: 'Ruthie',                 category: 'Script' },
  { name: 'Stalemate',              category: 'Script' },
  { name: 'Herr Von Muellerhoff',   category: 'Script' },
  { name: 'Engagement',             category: 'Script' },
  { name: 'Qwigley',                category: 'Script' },
  { name: 'Clicker Script',         category: 'Script' },

  // Serif
  { name: 'Playfair Display',       category: 'Serif' },
  { name: 'Merriweather',           category: 'Serif' },
  { name: 'Lora',                   category: 'Serif' },
  { name: 'Cormorant Garamond',     category: 'Serif' },
  { name: 'IM Fell English',        category: 'Serif' },
  { name: 'Libre Baskerville',      category: 'Serif' },
  { name: 'Crimson Text',           category: 'Serif' },
  { name: 'Josefin Slab',           category: 'Serif' },
  { name: 'Arvo',                   category: 'Serif' },
  { name: 'Bitter',                 category: 'Serif' },
  { name: 'Abril Fatface',          category: 'Serif' },
  { name: 'Domine',                 category: 'Serif' },
  { name: 'Spectral',               category: 'Serif' },
  { name: 'Cardo',                  category: 'Serif' },

  // Sans-Serif
  { name: 'Montserrat',             category: 'Sans' },
  { name: 'Raleway',                category: 'Sans' },
  { name: 'Poppins',                category: 'Sans' },
  { name: 'Nunito',                 category: 'Sans' },
  { name: 'Josefin Sans',           category: 'Sans' },
  { name: 'Quicksand',              category: 'Sans' },
  { name: 'Comfortaa',              category: 'Sans' },
  { name: 'Exo 2',                  category: 'Sans' },
  { name: 'Varela Round',           category: 'Sans' },

  // Arabic
  { name: 'Amiri',                  category: 'Arabic', sample: 'توقيع' },
  { name: 'Cairo',                  category: 'Arabic', sample: 'توقيع' },
  { name: 'Tajawal',                category: 'Arabic', sample: 'توقيع' },
  { name: 'Scheherazade New',       category: 'Arabic', sample: 'توقيع' },
  { name: 'Noto Naskh Arabic',      category: 'Arabic', sample: 'توقيع' },
  { name: 'Lateef',                 category: 'Arabic', sample: 'توقيع' },
  { name: 'Reem Kufi',              category: 'Arabic', sample: 'توقيع' },
  { name: 'El Messiri',             category: 'Arabic', sample: 'توقيع' },
  { name: 'Lalezar',                category: 'Arabic', sample: 'توقيع' },
  { name: 'Mada',                   category: 'Arabic', sample: 'توقيع' },
  { name: 'Katibeh',                category: 'Arabic', sample: 'توقيع' },
  { name: 'Jomhuria',               category: 'Arabic', sample: 'توقيع' },
  { name: 'Harmattan',              category: 'Arabic', sample: 'توقيع' },
  { name: 'Aref Ruqaa',             category: 'Arabic', sample: 'توقيع' },
  { name: 'Rakkas',                 category: 'Arabic', sample: 'توقيع' },

  // CJK
  { name: 'Noto Serif SC',          category: 'CJK', sample: '签名' },
  { name: 'Noto Sans SC',           category: 'CJK', sample: '签名' },
  { name: 'ZCOOL XiaoWei',          category: 'CJK', sample: '签名' },
  { name: 'Ma Shan Zheng',          category: 'CJK', sample: '签名' },
  { name: 'Zhi Mang Xing',          category: 'CJK', sample: '签名' },
  { name: 'Long Cang',              category: 'CJK', sample: '签名' },
  { name: 'ZCOOL KuaiLe',           category: 'CJK', sample: '签名' },
  { name: 'Noto Serif JP',          category: 'CJK', sample: '署名' },
  { name: 'Noto Sans JP',           category: 'CJK', sample: '署名' },
  { name: 'Zen Kurenaido',          category: 'CJK', sample: '署名' },
  { name: 'Noto Serif KR',          category: 'CJK', sample: '서명' },
  { name: 'Noto Sans KR',           category: 'CJK', sample: '서명' },
  { name: 'Nanum Myeongjo',         category: 'CJK', sample: '서명' },
  { name: 'Gowun Dodum',            category: 'CJK', sample: '서명' },

  // Other scripts
  { name: 'Tiro Devanagari Hindi',  category: 'Other', sample: 'हस्ताक्षर' },
  { name: 'Mukta',                  category: 'Other', sample: 'हस्ताक्षर' },
  { name: 'Yatra One',              category: 'Other', sample: 'हस्ताक्षर' },
  { name: 'Baloo 2',                category: 'Other', sample: 'हस्ताक्षर' },
  { name: 'Heebo',                  category: 'Other', sample: 'חתימה' },
  { name: 'Frank Ruhl Libre',       category: 'Other', sample: 'חתימה' },
  { name: 'Suez One',               category: 'Other', sample: 'חתימה' },
  { name: 'Noto Serif Thai',        category: 'Other', sample: 'ลายเซ็น' },
  { name: 'Sarabun',                category: 'Other', sample: 'ลายเซ็น' },
  { name: 'Kodchasan',              category: 'Other', sample: 'ลายเซ็น' },
  { name: 'Noto Serif Bengali',     category: 'Other', sample: 'স্বাক্ষর' },
  { name: 'Hind Siliguri',          category: 'Other', sample: 'স্বাক্ষর' },
]
